# -*- coding: utf-8 -*-

"""
    collection

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class PartyIdTypeEnum(object):

    """Implementation of the 'PartyIdType' enum.

    TODO: type enum description here.

    Attributes:
        MSISDN: TODO: type description here.
        EMAIL: TODO: type description here.
        PARTY_CODE: TODO: type description here.

    """

    MSISDN = 'MSISDN'

    EMAIL = 'EMAIL'

    PARTY_CODE = 'PARTY_CODE'

