# -*- coding: utf-8 -*-

"""
    collection

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class StatusEnum(object):

    """Implementation of the 'Status' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        SUCCESSFUL: TODO: type description here.
        FAILED: TODO: type description here.

    """

    PENDING = 'PENDING'

    SUCCESSFUL = 'SUCCESSFUL'

    FAILED = 'FAILED'

