# -*- coding: utf-8 -*-

"""
    collection

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class CodeEnum(object):

    """Implementation of the 'Code' enum.

    TODO: type enum description here.

    Attributes:
        PAYEE_NOT_FOUND: TODO: type description here.
        PAYER_NOT_FOUND: TODO: type description here.
        NOT_ALLOWED: TODO: type description here.
        NOT_ALLOWED_TARGET_ENVIRONMENT: TODO: type description here.
        INVALID_CALLBACK_URL_HOST: TODO: type description here.
        INVALID_CURRENCY: TODO: type description here.
        SERVICE_UNAVAILABLE: TODO: type description here.
        INTERNAL_PROCESSING_ERROR: TODO: type description here.
        NOT_ENOUGH_FUNDS: TODO: type description here.
        PAYER_LIMIT_REACHED: TODO: type description here.
        PAYEE_NOT_ALLOWED_TO_RECEIVE: TODO: type description here.
        PAYMENT_NOT_APPROVED: TODO: type description here.
        RESOURCE_NOT_FOUND: TODO: type description here.
        APPROVAL_REJECTED: TODO: type description here.
        EXPIRED: TODO: type description here.
        TRANSACTION_CANCELED: TODO: type description here.
        RESOURCE_ALREADY_EXIST: TODO: type description here.

    """

    PAYEE_NOT_FOUND = 'PAYEE_NOT_FOUND'

    PAYER_NOT_FOUND = 'PAYER_NOT_FOUND'

    NOT_ALLOWED = 'NOT_ALLOWED'

    NOT_ALLOWED_TARGET_ENVIRONMENT = 'NOT_ALLOWED_TARGET_ENVIRONMENT'

    INVALID_CALLBACK_URL_HOST = 'INVALID_CALLBACK_URL_HOST'

    INVALID_CURRENCY = 'INVALID_CURRENCY'

    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'

    INTERNAL_PROCESSING_ERROR = 'INTERNAL_PROCESSING_ERROR'

    NOT_ENOUGH_FUNDS = 'NOT_ENOUGH_FUNDS'

    PAYER_LIMIT_REACHED = 'PAYER_LIMIT_REACHED'

    PAYEE_NOT_ALLOWED_TO_RECEIVE = 'PAYEE_NOT_ALLOWED_TO_RECEIVE'

    PAYMENT_NOT_APPROVED = 'PAYMENT_NOT_APPROVED'

    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'

    APPROVAL_REJECTED = 'APPROVAL_REJECTED'

    EXPIRED = 'EXPIRED'

    TRANSACTION_CANCELED = 'TRANSACTION_CANCELED'

    RESOURCE_ALREADY_EXIST = 'RESOURCE_ALREADY_EXIST'

